### ISSUE TITLE
Sistema di autenticazione

### ISSUE THREAD

**Issue by CeccoGab** [edoardomazzon/battleship-game#2]
Implementare la registrazione di un utente con hash della password + sistema di login che lo reindirizzi nella home page, e per verificare che sia dentro la homepage loggato stampare il suo nome nella homepage

**Comment by thomasvisentin** [comment]
Registrazione di un utente con hash della password OK
Creato login.service.ts e model login (struttura del json contenente le sole informazioni per il login cioè username e password), rimane verifica correttezza password lato server (login.js) e creazione maschera inserimento username e password (pensavo magari inserimento dati in home.html e visualizzazione dati utente loggato in login.html)

**Comment by CeccoGab** [comment]
Form di Login con username e password fatti, riusciti a verificare col db che username e password siano giusti (o sbagliati), manca da implementare la sessione di un utente, quindi farlo effettivamente loggare.
Si potrebbe testare l'avvio della sessione reindirizzando l'utente alla homepage dopo il login e stampando il suo nome utente.

**Comment by CeccoGab** [comment]
Aggiunto sistema di autenticazione con token salvato in localstorage e anche sistema di prevenzione di accesso alle route se non si è loggati (e anche alle route login e register se si è già loggati) e alle route admin se non si è admin
