### ISSUE TITLE
Friends List

### ISSUE THREAD

**Issue by CeccoGab** [edoardomazzon/battleship-game#3]
Aggiungere al model di MongoDB di User anche i campi  pending_friend_requests  (lista di username quindi lista di stringhe) e friends_list (lista di username quindi lista di stringhe). Quando un utente A invia una richiesta di amicizia all'utente B, lo username di A finisce nella pending_friend_requests di B. Se B accetta, viene fatta una UPDATE su le friends_list di A e B aggiungendo i reciproci username. Se invece B rifiuta, semplicemente viene rimosso lo username di A dalla sua pending_friend_request.

Volendo possiamo valutare di implementare anche la funzione Block User senza dover per forza notificare l'utente bloccato, che potrà comunque inviare richieste di amicizia ma che finiranno a vuoto senza mai arrivare all'utente che l'ha bloccato.

**Comment by CeccoGab** [comment]
Siamo riusciti a modificare con una POST la pending_friend_requests di un utente aggiungendo il nome del mittente della richiesta nella lista delle friend request del destinatario.

Prossime modifiche:
  - controllare che la richiesta non sia già stata fatta (ovvero vedere se nella pendingfriendrequests non ci sia già il nome utente del mittente
  - implementare il rifiuto della richiesta (con route dedicata)
  - implementare l'accettazione della richiesta (con rout dedicata)
  - implementare il blocco di un altro utente e provare a fare poi delle richieste (che si potranno comunque fare ma non andranno da nessuna parte)

**Comment by CeccoGab** [comment]
Fatta la blacklist e fatta la reject di una friend request.
Se B chiede l'amicizia ad A ma B è stato messo in blacklist da A, allora la friend request di B va a vuoto e nessuno vede niente.
Ora ho fatto in modo, finché non abbiamo socket.io, che quando rifiutiamo o banniamo qualcuno, viene riscritto il localstorage con i nuovi dati (cioè le nuove liste di richieste di amicizia o di blacklist) e si ricarica la pagina.
Quando avremo socket.io sarà tutto più dinamico e non dovremo ricaricare la pagina.

**Comment by edoardomazzon** [comment]
- [ ] Pene 

- [ ] con i nuovi dati (cioè le nuove liste di richieste di amicizia o di blacklist) e si ricarica la pagina.
Quando avremo socket.io sarà tutto più dinamico e non dovremo ricaricare la pagina.

- [ ] 

- [ ]
